### ISSUE TITLE
M&L BiS minor graphical bugs

### ISSUE THREAD

**Issue by hubert-skowronek** [ahezard/nds-bootstrap#485]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release 0.14.0 RC1
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

M&L BiS

### Expected behaviour

There shouldn't be any flickering in the upper screen

### Actual behaviour

Sometimes, when there is some animated scene the upperscreen flickers (on the beginning when the player is introduced to the story and screenshots of blorbs are shown, later when Bowser drinks water and Bros. take control in his guts, when Fawful has its show in Bowser's castle and it begins). There is also similar issue nearly before every fight, when there is that introductory animation with stars falling down but after they fall to the bottom screen the one flickers in the upper screen.

### Steps to reproduce

1. Play ML BiS with nds bootstrap 0.14.0 RC1
2. Proceed to any mentioned stages of the game
3. Observe flickering (horizontal bars)

**Comment by NightYoshi370** [comment]
a) what are your settings
b) Which AP patch are you using?

**Comment by hubert-skowronek** [comment]
a) kinder_bueno patch
b) default settings, but tried using DSi mode, vsync on and it didn't help

**Comment by ahezard** [comment]
could be linked to #554 that have been fixed. Please retest with the latest nightly.

**Comment by hubert-skowronek** [comment]
@ahezard tested with the latest nightly, issues still occur, e.g. when Mario gets puzzle element for the new attack technique then flickering bars appear, when enemy approach and falling-stars screen appears then it also flickers sometimes (stars which fell remain for a moment at the top screen)

**Comment by Kaisaan** [comment]
Does this still happen on the latest version (0.32.1)? Seems that the battle start animation doesn't flicker/glitch for me. Tested this on my DSi XL.
