### ISSUE TITLE
Lag in Pokémon Mystery Dungeon: Blue Rescue Team

### ISSUE THREAD

**Issue by meoxx** [ahezard/nds-bootstrap#587]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [X]  Nightly 279a9cc

### If this issue only affects a certain game, which game is it

Pokémon Mystery Dungeon: Blue Rescue Team

### Expected behaviour

The attacks and screen that shows the next floor of the dungeon should appear without lag

### Actual behaviour

It lags on the attacks and screen that shows the next floor of the dungeon. For example, I select an attack, the game lags for a few seconds, the attack happens. An example for he screen that shows the next floor of the dungeon is that I reach the stairs and nothing happens for a few seconds before the screen showing the floor for the next dungeon appears

### Steps to reproduce

1. Boot up game
2. Enter dungeon
3. Perform attack or reach stairs

**Comment by RocketRobz** [comment]
Try updating the nds-bootstrap nightly using the TWiLight Menu++ updater.

**Comment by meoxx** [comment]
There’s a little less lag now

**Comment by RocketRobz** [comment]
Can you try with latest TWLMenu++ and nds-bootstrap versions?

**Comment by meoxx** [comment]
There is less lag for the attacks and dungeon floor loading thing now

**Comment by RocketRobz** [comment]
I assume this is fixed.

**Comment by ChainSwordCS** [comment]
I'm still seeing this issue on the latest nightly release.

Which is a little odd... I didn't notice any issues with this lag at all when I first started playing but it started later and by now (1 hour ish of play time) it's very distracting. I wonder if it's related to having a save file. I've tried changing settings to no avail.

**Comment by ChainSwordCS** [comment]
Upon further testing, the lag got really bad sometime after v0.36.0 and before v0.37.0

In v0.36.0 I noticed the lag isn't completely gone, it's reduced to be more microstutter-ish. Reducing it to be less or none would be nice.

And when I said I didn't notice the lag when I started playing, I actually updated nds-bootstrap after I started the game.

**Comment by NaturalHarmonia** [comment]
Man I thought I was crazy and that Rescue Team was always a little laggy but it seems I wasn't.
