### ISSUE TITLE
Final fantasy 3 regression - release 23.0 work but 24.0 not work

### ISSUE THREAD

**Issue by tomudo** [ahezard/nds-bootstrap#748]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x ]  Release 23.0 / 24.0
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Final fantasy 3

### Expected behaviour

Game run normally.

### Actual behaviour

game freeze after start logo

### Steps to reproduce

1. copy nds-bootstrap-hb-release.nds and nds-bootstrap-release.nds to /_nds
2. run game
3. game freeze after logo

**Comment by RocketRobz** [comment]
What's your flashcard?

**Comment by tomudo** [comment]
> 
> 
> What's your flashcard?

I'm not use flashcard. Final Fantasy 3 runs from SD card.

**Comment by RocketRobz** [comment]
You marked `(Slot-1) Flashcard` as your device though.

Try holding L after pressing A/START to launch the game.

**Comment by tomudo** [comment]
> 
> 
> You marked `(Slot-1) Flashcard` as your device though.
> 
> Try holding L after pressing A/START to launch the game.

Sorry, that is my incorrect mark. :/  

I tried as your suggestion but it still freezes.

**Comment by PurpleHazeFeedback** [comment]
I assume you're using TWiLight Menu++, correct? If so, when hovering over the Final Fantasy 3, press Y, then a small menu/tab will open, then press X to open up the cheats; the first cheat is called "save checksum bypass code", press A to select it and press X to save this config. This "cheat" acts as a bypass and now you can play the game again, hopefully. If you don't have the cheat database in your SD card, you can get them from here: https://github.com/DeadSkullzJr/NDS-Cheat-Databases/releases

**Comment by tomudo** [comment]
> 
> 
> I assume you're using TWiLight Menu++, correct? If so, when hovering over the Final Fantasy 3, press Y, then a small menu/tab will open, then press X to open up the cheats; the first cheat is called "save checksum bypass code", press A to select it and press X to save this config. This "cheat" acts as a bypass and now you can play the game again, hopefully. If you don't have the cheat database in your SD card, you can get them from here: https://github.com/DeadSkullzJr/NDS-Cheat-Databases/releases and you can use this tutorial on youtube if you dont know what to put where and so on https://www.youtube.com/watch?v=fRpFM6Fmsjo

It works. Thank you.

**Comment by PurpleHazeFeedback** [comment]
Glad I could help!

**Comment by ahezard** [comment]
So it is not a nds-bootstrap issue? I do not understand how a cheat can fix this issue.

**Comment by PurpleHazeFeedback** [comment]
> 
> 
> So it is not a nds-bootstrap issue? I do not understand how a cheat can fix this issue.

Well, it seems to be, because sure enough I tried FF3 on 23.0 and it works fine without the cheat, but on 24.0 I got the same issue as Tomudo, which can only be fixed by the "save checksum bypass".

**Comment by RocketRobz** [comment]
Does the bug persist in v0.26.1?

**Comment by tomudo** [comment]
I tested it. Bug behavior is changed.

It freezes  video after logo. But If it passes movie by press start then the game runs fine.

This time ap fix (save checksum bypass code) cheat code still freeze at video after logo too.

**Comment by RocketRobz** [comment]
Haven't gotten this bug, last time I tested.
