### ISSUE TITLE
Games don't load with cheats, include AP cheat

### ISSUE THREAD

**Issue by AdeptusCustodes** [ahezard/nds-bootstrap#826]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Pokemon HGSS

### Expected behaviour

Game should load with cheats

### Actual behaviour

If any cheats is active, including AP cheat, the white screens appear instead game loading.

### Steps to reproduce

1. Install last usrcheat,dat file.
2. Make any cheat active.
3. White screen.

**Comment by NightYoshi370** [comment]
Fixed in 0.29.3

**Comment by AdeptusCustodes** [comment]
> Fixed in 0.29.3

I update the bootstrap with latest version, and HGSS still wont loading, instead white screen appears.

**Comment by NightYoshi370** [comment]
It's probably more of a support error, since I don't believe others can reproduce this. Let's talk on the discord server found in the ReadME
